### ISSUE TITLE
윈도우 버전 10이 8로 나오는 문제

### ISSUE THREAD

**Issue by ghost** [kosslab-kr/GSharp#1]
![20171017_194940](https://user-images.githubusercontent.com/19469996/31661317-38d4c732-b375-11e7-8e75-c0c3791382cb.png)

위 사진과 같이 윈도우 버전이 정확하게 나오지 않습니다.
[https://ko.wikipedia.org/wiki/%EC%9C%88%EB%8F%84%EC%9A%B0_NT](url) 윈도우 10은 NT 10.0 이라고 해서 버전 결과가 정확하지 않은 것 같습니다.

**Comment by iodes** [comment]
378abca30ae17b99f836376e4f83335c99a79191 : 앱 매니페스트 수정
