### ISSUE TITLE
레지스트리 수정 모듈 개발

### ISSUE THREAD

**Issue by ghost** [kosslab-kr/GSharp#11]
레지스트리를 수정할 수 있는 모듈 개발하겠습니다.

**Comment by iodes** [comment]
관리자 권한 접근이 필요할 수도 있을 것 같습니다.
이 부분은 필요하다면 컴파일러 기능 확장이 필요할 것 같아요.

**Comment by ghost** [comment]
@iodes  컴파일러 실행할 때 관리자 권환으로 실행하는 것은 app.mainifest에서 설정하면되는데 관리자 권환을 요구하는 블록을 만들라는 말씀이신가요?

**Comment by iodes** [comment]
관리자 권한 관련 이슈는 #19 를 참고해주세요.

**Comment by ghost** [comment]
삭제는 개발 완료.
모듈에 적용 완료됨. [https://github.com/kosslab-kr/GSharp.Modules](url)
