### ISSUE TITLE
블록 드래그 앤 드롭이 잘 안되는 문제

### ISSUE THREAD

**Issue by ghost** [kosslab-kr/GSharp#13]
블록이 드래그 앤 드롭이 되다가 안되거나 처음부터 안되는 경우가 있습니다.

GSharp\GSharp.Extension\Abstracts\GView.cs(11,44,11,49): warning CS0109: 'GView.Click' 멤버는 액세스 가능한 멤버를 숨기지 않으므로 new 키워드가 필요하지 않습니다. 이것과 관련 있는거 같기도 합니다.

**Comment by ghost** [comment]
GSharp\GSharp.Extension\Abstracts\GView.cs 에서 

`public new event ClickEventHandler Click;`

`public event ClickEventHandler Click;` 로 수정했는데 동일 증상이 나타나네요.. 

이벤트쪽 문제 같은데..

**Comment by ghost** [comment]
현재까지 연구 결과
GSharp.Moudle.모듈이름.ini에서
`[General]
Title=파일`
Title 부분이 다른 블록이 들어가거나 호출(정확한 표현인지는 모르겠네요.) 되면 오류가 납니다.

**Comment by ghost** [comment]
Title이 같아도 동일 오류가 발생합니다...

![20171024_175106](https://user-images.githubusercontent.com/19469996/31933483-32e8757a-b8e4-11e7-9f2b-2fabbe45251b.png)

![20171024_175152](https://user-images.githubusercontent.com/19469996/31933496-38ada548-b8e4-11e7-951e-6a2cca8df2de.png)

위사진으로 봤을 때와 가끔 블록이 2개로 복사되는 것보면 아직 내부적으로 불록 호출 중이여서 사용자 입장에서는 블록이 드래그 앤 드롭이 안 되고 있는 것처럼 보이는 것 같습니다.

**Comment by ghost** [comment]
동일 이슈인지는 모르겠지만, 블록 상자에 있는 블록을 블록 스크립트에 있는 블록 홀에 스치면 복사되는 버그도 있습니다. (랜덤하게 발생)

**Comment by ghost** [comment]
`public event EventHandler Click` 이슈로 너무 빠르게 하거나 블록을 더블 클릭 후 드래그 앤 드롭하면 생기는 문제입니다.

[https://msdn.microsoft.com/ko-kr/library/system.windows.forms.control.click(v=vs.110).aspx](url) 참고해주세요.

**Comment by iodes** [comment]
3feae23ee887dea76add1aec3bcaf01b7795ebc2
blockEditor_DragEnter 이벤트가 비동기로 설정되어있어 이벤트 순서가
서로 바뀌면서 발생되는 오류였습니다. 해당 내용 수정하였습니다.
