### ISSUE TITLE
콘솔 모듈 불러올 경우

### ISSUE THREAD

**Issue by hubeen** [kosslab-kr/GSharp#14]
콘솔 모듈 불러올 경우 드래그드랍이 안되는 이슈가 일어납니다.

**Comment by ghost** [comment]
GSharpSample에서 하신건가요? 구체적인 환경도 알려주세요.

여러 가지 방법으로 시도 중인데 드래그 앤 드롭이 안되는 이슈가 특정 모듈에서만 나타나고 있지가 않거든요. 

#13 참고 부탁드립니다.

**Comment by hubeen** [comment]
GSharpSample에서 했습니다.
가상환경 parall에서 윈도우7로 디버깅하여 사용하였습니다.
OS : Windows7 (Parall)

콘솔 모듈을 불러오면 드래그 드랍이 안되더라구요.
이제보니 특정 모듈에서만 일어나는 이슈가 아닌 것 같네요!

**Comment by iodes** [comment]
현재 모든 블럭에서 발생하는것으로 확인되고 있습니다.
본 이슈는 #13 이슈로 통합하고 클로즈하도록 하겠습니다.
