### ISSUE TITLE
콘솔 모듈에서 '입력된 문자' 가 타 모듈과 매칭이 안되는 이슈

### ISSUE THREAD

**Issue by BEMELON** [kosslab-kr/GSharp#15]
![console error](https://user-images.githubusercontent.com/25559854/31937525-b14a46ae-b8ef-11e7-94ac-95060acf1a29.jpg)

대부분의 블록에 대해서 테스트를 하였는데, 어느 블록은 매칭이 되고 어느 블록은 매칭이 되지 않습니다.

현재 '입력된 문자' 아래에 있는 블록들은 매칭이 되지 않습니다. 

테스트 환경은 Lynx Studio 입니다.

**Comment by BEMELON** [comment]
![console error2](https://user-images.githubusercontent.com/25559854/31937908-da739f02-b8f0-11e7-8b5d-c18892aa08a2.jpg)

순서가 일정해야 블록이 들어가는 이슈 가 더 정확한 이슈 이름일거 같습니다 ㅎㅎ

조금 더 확인해봤는데

'콘솔에 입력된 경우' 아래에 블록을 붙여야만 그 블록에 '입력된 문자' 가 매칭이 됩니다.

**Comment by iodes** [comment]
해당 블럭은 이벤트 블럭으로써 다음과 같은 형태의 네이티브 코드로 구성되어있습니다.

```CSharp
[GCommand("콘솔에 입력된 경우")]
public static event ReceivedEventHandler Received;
public delegate void ReceivedEventHandler([GParameter("입력된 문자")] string value);
```

여기서 입력된 문자는 ReceivedEventHandler 핸들러에서 전달되는 string value 매개 변수를 뜻합니다.
이 매개 변수는 함수와 동일하게 핸들러 밖에서 사용하는것이 불가능하기 때문에 블록 코딩 또한
해당 이벤트 블록에 연결된 곳에서만 입력된 문자를 사용할 수 있게 설계되어있습니다.

즉, 해당 현상은 버그가 아니며 개발 단계에서 의도된 설계입니다.
해당 인자를 핸들러 밖에서 사용하려면 전역 변수를 생성하여 할당해주셔야 합니다.

다만 이 부분을 조금 더 명확히 할 수 있도록 도움말등을 추가하는
개선 작업을 진행하면 좋을 것 같습니다. 이슈 제출 감사드립니다.

**Comment by ghost** [comment]
앗! 댓글 달고있는데 멘토님이 먼저 댓글 달아주셨군요.

블록을 놓고 네이트브 코드를 보면서 변화를 관찰하시면 쉽게 이해하실 수 있으실 것입니다.
