### ISSUE TITLE
관리자 권환으로 실행 기능 모듈

### ISSUE THREAD

**Issue by ghost** [kosslab-kr/GSharp#19]
관리자 권환으로 실행 기능 모듈이 필요해서 제작합니다.

**Comment by ghost** [comment]
c# uac bypass를 하기 위해서 미니패스트 파일 수정이 아니면 레지스트리 수정 하게 하는 방법이 있는데 레지스트리 수정은 파일 uac요구가 아닌 아에 uac를 레지스트리를 수정해서 낮추는 것 같습니다.

**Comment by iodes** [comment]
https://goo.gl/UDXPDY
급한대로 간단하게 한번 구현해보았습니다.

해당 모듈은 164224225518ef14bdcd9f38107ac4fc7b1bdea4 커밋에 추가되었습니다.
확인해보시고 수정 하실 부분은 수정 해주시면 감사하겠습니다.

**Comment by ghost** [comment]
@iodes 오~ 저런 방법이 있었군요. 배워갑니다.

**Comment by ghost** [comment]
우선, 발견된 문제는 없고 이미 커밋되어있음으로 Close합니다.
